obstacle_range: 2.5 # parameter determines the maximum range sensor reading that will result in an obstacle being put into the costmap
raytrace_range: 3.0 # determines the range to which we will raytrace freespace given a sensor reading
footprint: [[-.117475, -.14605], [-.117475, .14605],  [.117475, .14605], [.117475, -.14605]] # footprint of spooky tank chassis with center at 0,0
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: laser_scan_sensor 

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

# point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}